version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"     
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    assignees:
      - endixons

  - package-ecosystem: "gradle"
    directory: "/common"   
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps-common"
    assignees:
      - endixons

  - package-ecosystem: "gradle"
    directory: "/proxy"  
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps-proxy"
    assignees:
      - endixons

  - package-ecosystem: "gradle"
    directory: "/paper" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps-paper"
    assignees:
      - endixons

  - package-ecosystem: "gradle"
    directory: "/tools" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps-tools"
    assignees:
      - endixons
